name: OreRandomizer
version: "1.8.0"
api-version: 1.13
main: io.github.crusopaul.OreRandomizer.OreRandomizer
commands:
  GetRandomizationSound:
    description: Displays the sound that plays when ore is randomly generated.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetRandomizationSound"
  SetRandomizationSound:
    description: Sets the sound that plays when ore is randomly generated for the specified sound.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /SetRandomizationSound <sound>"
  SetOreRatio:
    aliases: [or.set]
    description: Sets the randomization ratio for the specified ore.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /SetOreRatio <ore> <ratio>"
  GetOreRatio:
    aliases: [or.get]
    description: Displays the randomization ratio for all ores, or one ore if specified.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetOreRatio [ore]"
  AddNewWorld:
    description: Allows OreRandomizer to be active for a specified world.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /AddNewWorld <world>"
  GetAllowedWorlds:
    description: Displays a list of worlds or a specified world that OreRandomizer is active for.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetAllowedWorlds [world]"
  RemoveAllowedWorld:
    description: Makes OreRandomizer inactive for a specified world.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /RemoveAllowedWorld <world>"
  GetObsidianToggle:
    description: Displays the current randomization behavior upon lava/water interaction that would lead to the creation of obsidian in vanilla MC.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetObsidianToggle"
  SetObsidianToggle:
    description: Sets the randomization behavior upon lava/water interaction that would lead to the creation of obsidian in vanilla MC.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /SetObsidianToggle <value>"
  GetStoneToggle:
    description: Displays the current randomization behavior upon lava/water interaction that would lead to the creation of stone in vanilla MC.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /GetStoneToggle"
  SetStoneToggle:
    description: Sets the randomization behavior upon lava/water interaction that would lead to the creation of stone in vanilla MC.
    permission-message: You do not have permission to use this command.
    usage: "Usage: /SetStoneToggle <value>"
permissions:
  OreRandomizer.ToggleCreeperSound:
    description: Allows you to use the command ToggleCreeperSound.
    default: true
  OreRandomizer.GetRandomizationSound:
    description: Allows you to use the command GetRandomizationSound.
    default: true
  OreRandomizer.SetRandomizationSound:
    description: Allows you to use the command SetRandomizationSound.
    default: true
  OreRandomizer.SetOreRatio:
    description: Allows you to use the command SetOreRatio.
    default: true
  OreRandomizer.GetOreRatio:
    description: Allows you to use the command GetOreRatio.
    default: true
  OreRandomizer.AddNewWorld:
    description: Allows you to use the command AddNewWorld.
    default: true
  OreRandomizer.GetAllowedWorlds:
    description: Allows you to use the command GetAllowedWorlds.
    default: true
  OreRandomizer.RemoveAllowedWorld:
    description: Allows you to use the command RemoveAllowedWorld.
    default: true
  OreRandomizer.GetObsidianToggle:
    description: Allows you to use the command GetObsidianToggle
    default: true
  OreRandomizer.SetObsidianToggle:
    description: Allows you to use the command SetObsidianToggle
    default: true
  OreRandomizer.GetStoneToggle:
    description: Allows you to use the command GetStoneToggle
    default: true
  OreRandomizer.SetStoneToggle:
    description: Allows you to use the command SetStoneToggle
    default: true
  OreRandomizer.*:
    description: Wildcard permission.
    default: false
    children:
      OreRandomizer.ToggleCreeperSound: true
      OreRandomizer.GetRandomizationSound: true
      OreRandomizer.SetRandomizationSound: true
      OreRandomizer.SetOreRatio: true
      OreRandomizer.GetOreRatio: true
      OreRandomizer.AddNewWorld: true
      OreRandomizer.GetAllowedWorlds: true
      OreRandomizer.RemoveAllowedWorld: true
      OreRandomizer.GetObsidianToggle: true
      OreRandomizer.SetObsidianToggle: true
      OreRandomizer.GetStoneToggle: true
      OreRandomizer.SetStoneToggle: true
